name: CI-CD
run-name: Build, Test, Deploy
on:
  - push
  - workflow_dispatch # Permit manual initiation
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run test
      
      # Publish takes place only if new version tag
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: build # Path
          token: ${{ secrets.NPM_TOKEN }}
 